# Generated by Django 3.0.8 on 2020-11-07 16:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='category/')),
                ('description', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('tree_id', 'name'),
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название товара', max_length=400)),
                ('slug', models.SlugField(max_length=400)),
                ('provider', models.CharField(help_text='Поставщик', max_length=20)),
                ('vendor_code', models.CharField(help_text='Артикул, парт номер', max_length=200, unique=True)),
                ('vendor', models.CharField(blank=True, help_text='Производитель', max_length=200)),
                ('type_product', models.CharField(blank=True, help_text='Тип товара', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='product/')),
                ('format_fild', models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10')], help_text='A3,A4', max_length=50)),
                ('color_fild', models.CharField(blank=True, choices=[('BW', 'BW'), ('Color', 'Color')], help_text='BW, Color', max_length=50)),
                ('specifications', models.TextField(blank=True, help_text='Характеристики товара')),
                ('description', models.TextField(blank=True, help_text='Описание товара')),
                ('tags', models.CharField(blank=True, help_text='Список тегов, разделенных запятыми', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена входящая', max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, default=1, help_text='Остатоки')),
                ('available', models.BooleanField(default=True, help_text='Доступен ли к заказу')),
                ('start_action', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_action', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('action', models.BooleanField(default=False, help_text='Акции')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Цена со скидкой', max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='дата обновления')),
                ('category', models.ForeignKey(help_text='Каталог товара (расходные материалы, компьютеры и комплетующие и т д)', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
