# Generated by Django 3.0.8 on 2020-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, default='qw', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(db_index=True, default='qw', max_length=200),
        ),
    ]
