# Generated by Django 3.0.8 on 2020-11-07 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201107_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания')),
                ('usd', models.DecimalField(blank=True, decimal_places=2, help_text='Курс USD', max_digits=4)),
                ('eur', models.DecimalField(blank=True, decimal_places=2, help_text='Курс EUR', max_digits=4)),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uk',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(max_length=400)),
                ('type_service', models.CharField(blank=True, default='Заправка картриджа', help_text='Тип сервиса', max_length=200)),
                ('vendor_code', models.CharField(blank=True, max_length=200)),
                ('vendor', models.CharField(blank=True, help_text='Производитель', max_length=200)),
                ('vendor_model', models.CharField(blank=True, help_text='Модель', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='service/')),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Ключивые слова')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accessories', models.ManyToManyField(blank=True, editable=False, to='api.Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
