# Generated by Django 3.0.8 on 2020-11-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201107_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rates',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications_uk',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
