# Generated by Django 3.0.8 on 2020-11-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201107_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='action',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_fild',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='end_action',
        ),
        migrations.RemoveField(
            model_name='product',
            name='format_fild',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_action',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_product',
        ),
    ]
